site_name: Ping Viewer
theme:
  name: material
  palette:
    primary: 'light blue'
    accent: 'blue'
nav:
    - Quick Start: index.md
    - Viewer Guide:
        - Device Settings:
            - Ping1D: device-settings-ping1d.md
            - Ping360: device-settings-ping360.md
            - Firmware Update: firmware-update.md
        - Application Settings:
            - Display Settings: display-settings.md
            - Device Manager: device-manager.md
        - Notificiations and Updates: notifications-and-updates.md
        - Replay Data: replay-data.md
        - Application Information: application-information.md
        - Hotkeys and Shortcuts: hotkeys-and-shortcuts.md
        - Logging and User Files: logging-and-user-files.md
        - FAQ and Troubleshooting: faq-and-troubleshooting.md
    - Developers:
        - Build Instructions: build-instructions.md
        - Libraries and Tools: libraries-and-tools.md
extra_css:
    - css/center_images.css
site_dir: ping-viewer
